/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8djYnAlMyMi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Button } from "@/components/ui/button"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Calendar } from "@/components/ui/calendar"
import { Input } from "./input"
import { useState } from "react"

export default function MonthYear() {

const [year, setYear] = useState<number>();

const [month, setMonth] = useState<Date | null>(null);

  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button variant="outline" className=" justify-start text-left font-normal">
          <CalendarDaysIcon className="mr-1 h-4 w-4 -translate-x-1" />
          Pick a date
        </Button>
      </PopoverTrigger>
      <PopoverContent align="start" className="flex w-auto flex-col space-y-2 p-2">
        <div className="flex items-center space-x-2">
          <Select size="sm">
            <SelectTrigger>
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="2022">2022</SelectItem>
              <SelectItem value="2023">2023</SelectItem>
              <SelectItem value="2024">2024</SelectItem>
              <SelectItem value="2025">2025</SelectItem>
              <SelectItem value="2024">2024</SelectItem>
            </SelectContent>
          </Select>
          <Select size="sm">
            <SelectTrigger>
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="00">January</SelectItem>
              <SelectItem value="01">February</SelectItem>
              <SelectItem value="02">March</SelectItem>
              <SelectItem value="03">April</SelectItem>
              <SelectItem value="04">May</SelectItem>
              <SelectItem value="05">June</SelectItem>
              <SelectItem value="06">July</SelectItem>
              <SelectItem value="07">August</SelectItem>
              <SelectItem value="08">September</SelectItem>
              <SelectItem value="09">October</SelectItem>
              <SelectItem value="10">November</SelectItem>
              <SelectItem value="11">December</SelectItem>
            </SelectContent>
          </Select>
        </div>
        
      </PopoverContent>
    </Popover>
  )
}

function CalendarDaysIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}
